/* @flow */

export default {
  amount: require('app/assets/amount.png'),
  back: require('app/assets/back.png'),
  balance_negative: require('app/assets/balance_negative.png'),
  balance_positive: require('app/assets/balance_positive.png'),
  bill_name: require('app/assets/bill_name.png'),
  bills: require('app/assets/bills.png'),
  calendar: require('app/assets/calendar.png'),
  camera: require('app/assets/camera.png'),
  category: require('app/assets/category.png'),
  drinks: require('app/assets/drinks.png'),
  edit: require('app/assets/edit.png'),
  entertainment: require('app/assets/entertainment.png'),
  food: require('app/assets/food.png'),
  fuel: require('app/assets/fuel.png'),
  groceries: require('app/assets/groceries.png'),
  group: require('app/assets/group.png'),
  holiday: require('app/assets/holiday.png'),
  loan: require('app/assets/loan.png'),
  logo: require('app/assets/logo.png'),
  medicine: require('app/assets/medicine.png'),
  member: require('app/assets/member.png'),
  multiple_people: require('app/assets/multiple_people.png'),
  others: require('app/assets/category.png'),
  rent: require('app/assets/rent.png'),
  shopping: require('app/assets/shopping.png'),
  tick: require('app/assets/tick.png'),
  to_get: require('app/assets/to_get.png'),
  to_pay: require('app/assets/to_pay.png'),
  travel: require('app/assets/travel.png')
};
